CREATE TABLE IF NOT EXISTS analysis_tasks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  analysis_task_id VARCHAR(128) NOT NULL,
  conversation_id VARCHAR(128) NOT NULL,
  workspace_id VARCHAR(128) NOT NULL,
  user_id VARCHAR(128) NOT NULL,
  business_domain_id VARCHAR(128) NOT NULL,
  question TEXT NOT NULL,
  context_pack_json JSON NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL,
  UNIQUE KEY uq_analysis_tasks_analysis_task_id (analysis_task_id),
  KEY idx_analysis_tasks_conversation_id (conversation_id),
  KEY idx_analysis_tasks_workspace_id (workspace_id),
  KEY idx_analysis_tasks_business_domain_id (business_domain_id)
);

CREATE TABLE IF NOT EXISTS conversations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  conversation_id VARCHAR(128) NOT NULL,
  workspace_id VARCHAR(128) NOT NULL,
  user_id VARCHAR(128) NOT NULL,
  current_run_id VARCHAR(128) NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  updated_at VARCHAR(40) NOT NULL,
  UNIQUE KEY uq_conversations_conversation_id (conversation_id),
  KEY idx_conversations_workspace_id (workspace_id),
  KEY idx_conversations_current_run_id (current_run_id)
);

CREATE TABLE IF NOT EXISTS analysis_runs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  run_id VARCHAR(128) NOT NULL,
  workspace_id VARCHAR(128) NOT NULL,
  user_id VARCHAR(128) NOT NULL,
  analysis_task_id VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  phase VARCHAR(64) NOT NULL,
  outcome VARCHAR(64) NULL,
  waiting_for VARCHAR(64) NULL,
  created_at VARCHAR(40) NOT NULL,
  validating_at VARCHAR(40) NULL,
  queued_at VARCHAR(40) NULL,
  started_at VARCHAR(40) NULL,
  waiting_since VARCHAR(40) NULL,
  timeout_at VARCHAR(40) NULL,
  cancel_requested_at VARCHAR(40) NULL,
  cancelling_at VARCHAR(40) NULL,
  completed_at VARCHAR(40) NULL,
  failed_at VARCHAR(40) NULL,
  cancelled_at VARCHAR(40) NULL,
  expired_at VARCHAR(40) NULL,
  rejected_at VARCHAR(40) NULL,
  terminal_reason TEXT NULL,
  failure_code VARCHAR(128) NULL,
  retryable TINYINT(1) NULL,
  retry_of_run_id VARCHAR(128) NULL,
  original_run_id VARCHAR(128) NULL,
  UNIQUE KEY uq_analysis_runs_run_id (run_id),
  KEY idx_analysis_runs_workspace_id (workspace_id),
  KEY idx_analysis_runs_analysis_task_id (analysis_task_id)
);
