CREATE TABLE IF NOT EXISTS run_events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_id VARCHAR(128) NOT NULL,
  run_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  phase VARCHAR(64) NOT NULL,
  sequence INT NOT NULL,
  actor VARCHAR(128) NOT NULL,
  occurred_at VARCHAR(40) NOT NULL,
  summary TEXT NOT NULL,
  parent_event_id VARCHAR(128) NULL,
  ref_type VARCHAR(128) NULL,
  ref_id VARCHAR(128) NULL,
  error_code VARCHAR(128) NULL,
  error_message TEXT NULL,
  node_name VARCHAR(128) NOT NULL,
  agent_name VARCHAR(128) NOT NULL,
  tool_name VARCHAR(128) NULL,
  started_at VARCHAR(40) NULL,
  completed_at VARCHAR(40) NULL,
  UNIQUE KEY uq_run_events_event_id (event_id),
  UNIQUE KEY uq_run_events_run_sequence (run_id, sequence),
  KEY idx_run_events_run_id (run_id),
  KEY idx_run_events_event_type (event_type)
);
